### ISSUE TITLE
Docker install generating errors

### ISSUE THREAD

**Issue by mick-d** [mgoubran/MIRACL#24]
Hi,

The default install using Docker generates errors due to module `abc`. It seems there is an incompatibility between libraries based on python 2 and others based on python 3.

The error comes from `nibabel/externals/oset.py`:
```
Traceback (most recent call last):
  File "/opt/miniconda/bin/miracl", line 11, in <module>
    load_entry_point('MIRACL==1.1.0', 'console_scripts', 'miracl')()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/cli.py", line 17, in <module>
    from miracl.seg import cli_seg
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/seg/cli_seg.py", line 5, in <module>
    from miracl.seg import miracl_seg_feat_extract, miracl_seg_voxelize_parallel, miracl_seg_feats_cortex
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/seg/miracl_seg_voxelize_parallel.py", line 17, in <module>
    import nibabel as nib
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/__init__.py", line 63, in <module>
    from . import analyze as ana
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/analyze.py", line 87, in <module>
    from .volumeutils import (native_code, swapped_code, make_dt_codes,
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/volumeutils.py", line 24, in <module>
    from .externals.oset import OrderedSet
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/externals/oset.py", line 17, in <module>
    from collections.abc import MutableSet
ImportError: No module named abc
```

However fixing this error by changing `from collections.abc import MutableSet` to `from collections import MutableSet` generates another error:

```
Traceback (most recent call last):
  File "/opt/miniconda/bin/miracl", line 11, in <module>
    load_entry_point('MIRACL==1.1.0', 'console_scripts', 'miracl')()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/cli.py", line 17, in <module>
    from miracl.seg import cli_seg
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/seg/cli_seg.py", line 5, in <module>
    from miracl.seg import miracl_seg_feat_extract, miracl_seg_voxelize_parallel, miracl_seg_feats_cortex
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/seg/miracl_seg_voxelize_parallel.py", line 17, in <module>
    import nibabel as nib
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/__init__.py", line 70, in <module>
    from .loadsave import load, save
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/loadsave.py", line 18, in <module>
    from .imageclasses import all_image_classes
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/imageclasses.py", line 13, in <module>
    from .cifti2 import Cifti2Image
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/cifti2/__init__.py", line 20, in <module>
    from .parse_cifti2 import Cifti2Extension
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/cifti2/parse_cifti2.py", line 15, in <module>
    from .cifti2 import (Cifti2MetaData, Cifti2Header, Cifti2Label,
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/cifti2/cifti2.py", line 20, in <module>
    from collections.abc import MutableSequence, MutableMapping, Iterable
ImportError: No module named abc
```
And fixing this one by changing `from collections.abc` to `from collections` uncovers another error:

```
  File "/opt/miniconda/bin/miracl", line 11, in <module>
    load_entry_point('MIRACL==1.1.0', 'console_scripts', 'miracl')()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/cli.py", line 17, in <module>
    from miracl.seg import cli_seg
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/seg/cli_seg.py", line 5, in <module>
    from miracl.seg import miracl_seg_feat_extract, miracl_seg_voxelize_parallel, miracl_seg_feats_cortex
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/seg/miracl_seg_voxelize_parallel.py", line 17, in <module>
    import nibabel as nib
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/__init__.py", line 70, in <module>
    from .loadsave import load, save
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/loadsave.py", line 18, in <module>
    from .imageclasses import all_image_classes
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/imageclasses.py", line 13, in <module>
    from .cifti2 import Cifti2Image
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/cifti2/__init__.py", line 29, in <module>
    from .cifti2_axes import (Axis, BrainModelAxis, ParcelsAxis, SeriesAxis, LabelAxis, ScalarAxis)
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/cifti2/cifti2_axes.py", line 175, in <module>
    class Axis(abc.ABC):
AttributeError: 'module' object has no attribute 'ABC'
``` 

And fixing again this error by replacing `class Axis(abc.ABC):` with `class Axis(abc.ABCMeta('ABC', (), {})` uncovers another error:
```
  File "/opt/miniconda/bin/miracl", line 11, in <module>
    load_entry_point('MIRACL==1.1.0', 'console_scripts', 'miracl')()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/cli.py", line 17, in <module>
    from miracl.seg import cli_seg
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/seg/cli_seg.py", line 5, in <module>
    from miracl.seg import miracl_seg_feat_extract, miracl_seg_voxelize_parallel, miracl_seg_feats_cortex
  File "/opt/miniconda/lib/python2.7/site-packages/MIRACL-1.1.0-py2.7.egg/miracl/seg/miracl_seg_voxelize_parallel.py", line 17, in <module>
    import nibabel as nib
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/__init__.py", line 94, in <module>
    from . import streamlines
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/streamlines/__init__.py", line 7, in <module>
    from .array_sequence import ArraySequence
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/streamlines/array_sequence.py", line 89, in <module>
    class ArraySequence(object):
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/streamlines/array_sequence.py", line 76, in _define_operators
    _wrap(cls, op=op, inplace=False)
  File "/opt/miniconda/lib/python2.7/site-packages/nibabel-3.0.0rc1-py2.7.egg/nibabel/streamlines/array_sequence.py", line 70, in _wrap
    fn.__name__ = op
AttributeError: 'instancemethod' object has no attribute '__name__'
```

Etc.

**Comment by mgoubran** [comment]
Hi @mick-d, thanks for pointing this. The docker issue should be fixed now. please let us know if you're having other issues. The local install should also work fine and is tested. cheers
